name: '15'
timestamp: 1510971399
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1510971399
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-6166: 'System Messages'
  logo:
    logo-6181: 'Logo / Image'
    logo-8905: 'Logo / Image'
  menu:
    menu-1618: Menu
  social:
    social-1212: Social
  position:
    position-position-7172: Aside
    position-position-6924: Sidebar
  content:
    system-content-6238: 'Page Content'
  copyright:
    copyright-9813: Copyright
  horizontalmenu:
    horizontalmenu-7868: 'Horizontal Menu'
  totop:
    totop-8784: 'To Top'
  mobile-menu:
    mobile-menu-7031: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-7972: system-messages-7972
    logo-9608: logo-9608
    menu-6409: menu-6409
    social-3171: social-3171
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    position-position-4734: position-position-4734
    mainbar: mainbar
    system-content-1587: system-content-1587
    sidebar: sidebar
    position-position-3949: position-position-3949
    footer: footer
    logo-9571: logo-9571
    copyright-1736: copyright-1736
    horizontalmenu-9034: horizontalmenu-9034
    totop-8670: totop-8670
    offcanvas: offcanvas
    mobile-menu-5697: mobile-menu-5697
    system-messages-6166: system-messages-7972
    logo-6181: logo-9608
    menu-1618: menu-6409
    social-1212: social-3171
    position-position-7172: position-position-4734
    system-content-6238: system-content-1587
    position-position-6924: position-position-3949
    logo-8905: logo-9571
    copyright-9813: copyright-1736
    horizontalmenu-7868: horizontalmenu-9034
    totop-8784: totop-8670
    mobile-menu-7031: mobile-menu-5697
